Description: > 
    This Cloudformation template deploys my EKS cluster into my AWS environment 

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

Resources:

  EKSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: EKS Cluster Security Group
      VpcId:
        Fn::ImportValue: !Sub ${EnvironmentName}-VPCID

  EKSSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref EKSSecurityGroup
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535
      SourceSecurityGroupId: !Ref EKSSecurityGroup

  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - eks.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties: 
      Name: CapstoneProjectEKSCluster
      RoleArn: !GetAtt EKSClusterRole.Arn
      Version: '1.19'
      ResourcesVpcConfig: 
        SecurityGroupIds:
          - !Ref EKSSecurityGroup
        SubnetIds: 
          - subnet-0799ba35e1f455384
          - subnet-056137990f0107af9