apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskex-deployment
  labels:
    app: flaskex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskex
  template:
    metadata:
      labels:
        app: flaskex
    spec:
      containers:
      - name: flaskex-container
        image: 586771751035.dkr.ecr.us-east-1.amazonaws.com/udacity_capstone:main
        imagePullPolicy: Always
        ports:
        - containerPort: 80