apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskex-deployment-green
  labels:
    app: flaskex-deployment-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskex-green
  template:
    metadata:
      labels:
        app: flaskex-green
    spec:
      containers:
      - name: flaskex-container-green
        image: 586771751035.dkr.ecr.us-east-1.amazonaws.com/udacity_capstone:green
        imagePullPolicy: Always
        ports:
        - containerPort: 80